spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/su
    username: root
    password: mysql.com
  #session过期时间
  session:
    timeout: 86400